### PR TITLE
feat: moved ips.py from xrpl/tools; now writes data as json

### PR DESCRIPTION
**Pull request by kylegranger**
For chore, **moving common scripts into ziggurat-core:**
- created `ziggurat-core-scripts` folder
- moved `ips.py` here from `xrpl/tools` -- will be fetched by script in xrpl & algorand
- script has also been edited to write json data, rather than a `ips.rs` module source file (quality of life improvement)
- the path and name of file to be written has also changed: `tools/ips_list.json`
- this new file path is reflected in the sample invocations contained in the comments.

### CODE REVIEW

**Review by asmie — APPROVED** [review]
👍

**Review by Rqnsom — APPROVED** [review]
- `script has also been edited to write json data, rather than a ips.rs module source file (quality of life improvement)`

This should have been put in a separate commit (or PR) so it's clear what the changes are, now the whole file is all green 

But I trust you 😃
so LGTM without manual script diff check 👍

**Review by zeapoz — APPROVED** [review]
LGTM :+1:

**Comment by kylegranger** [comment]
@Rqnsom  I see your point.

**Pull request merged**
